### PR TITLE
refactor(SecureWindow): update import

### LINKED ISSUE #9: Update import format to XCode 14.2 compat
The import `#import "RCTUtils.h"` in `ios/SecureWindow.m` is causing issues in XCode 14.2. It looks like the same issue as this expo issue: https://github.com/expo/expo/issues/15622#issuecomment-997141629

For us, the expo workaround https://github.com/expo/expo/pull/15655 with `expo_patch_react_imports` isn't consistently working, so it would be great to change the import into `#import <React/RCTUtils.h>`.

Is that an option? Would you accept a PR for that?

---

This patch works for us:
```diff
diff --git a/node_modules/react-native-secure-window/ios/SecureWindow.m b/node_modules/react-native-secure-window/ios/SecureWindow.m
index b39613b..00843d2 100644
--- a/node_modules/react-native-secure-window/ios/SecureWindow.m
+++ b/node_modules/react-native-secure-window/ios/SecureWindow.m
@@ -1,5 +1,5 @@
 #import "SecureWindow.h"
-#import "RCTUtils.h"
+#import <React/RCTUtils.h>
 
 @implementation SecureWindow
 
```

### PR DESCRIPTION
**Pull request by jzaefferer**
Fixes #9

I ignored errors from prettier in example/src/App.tsx, since I didn't change anything there.

I couldn't test this with the example app, since that no longer works with XCode 14.2 and iPhone 14, but updating all that seemed way out of scope for this simple change.

I hope this is useful anyway.

### CODE REVIEW

**Review by NaeemCheema — APPROVED** [review]
Looks good to me

**Comment by jzaefferer** [comment]
@Ashwin-Mothilal could you take a look?

**Comment by Ashwin-Mothilal** [comment]
> @Ashwin-Mothilal could you take a look?

Sure will try to do this over the weekend.

**Review by Ashwin-Mothilal — APPROVED** [review]

**Comment by Ashwin-Mothilal** [comment]
I'm merge this pull request. I will create a new issue for updating the example app. As I'm not actively working on RN, requesting someone to update it, if no I will do it in my free time.

**Pull request merged**
